### ISSUE TITLE
Create syntax test

### ISSUE THREAD

**Issue by jkeiser** [berg-lang/berg#2]
Create a test that lets us check if syntax is working right. Just one test, 1+1 ... but do it in a way that lets us easily repeat and build more tests, and allows the tests to be run from multiple languages..

Current plan: tests/literals.yaml

```yaml
- Berg: "-12"
  Ast: StringLiteral: "-12"
  Result: String: "-12"
- Berg: -12
  Ast: IntegerLiteral: "-12"
  Result: Integer: -12
- Berg: -12.34e-45
  Ast: FloatLiteral: "-12.34e-45"
  Result: Float: -12.34e-45
- Berg: -012
  Ast: OctalLiteral: "-012"
  Result: Integer: -10
- Berg: -0x12
  Ast: HexadecimalLiteral: "-0x12"
  Result: Integer: 18
```
